language: csharp
solution: SimplCommerce.sln
sudo: required
dist: trusty
dotnet: 1.0.0
mono: none
os:
  - linux
  - osx
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=true

branches:  
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
  - dotnet restore

script:
  - dotnet build ./SimplCommerce.sln
  - ./run-tests.sh
